### ISSUE TITLE
Still a valid/worthwhile package to use? 

### ISSUE THREAD

**Issue by tomardern** [browsertron/jest-runner-concurrent#1]
Hi, 

This package looks pretty good and could improve the speed of our Jest Unit testing. 

Seems like the repo is pretty inactive (last commit 2 years) - is this still something worth trying/investigating? 

Thanks!

**Comment by kevlened** [comment]
Hi Tom, thanks for your interest. You're free to try, but I imagine jest has changed significantly, so it may not work. I'm not actively maintaining this  anymore and I'm not using it in my repos, so I'll update the description.

**Comment by tomardern** [comment]
Thanks for the swift, honest reply :)
